name: Simple Java Github Actions Experiment

on:
 push:
    branches:
        -dev-environment

jobs:
    build:
      runs-on: ubuntu-latest


      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: unix commands
          run: |
                mkdir build
                cd build
            
        - name: setting up java
          uses: actions/setup-java@v3
          with:
            distribution: 'oracle'
            java-version: '11'

        - name: Compiling code
          run: javac HelloWorld.java

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: 192.168.55.108
            username: "ANIRUDDHA MALLADI"
            password: "@10tatorS"
            port: 22
            script: |
                     whoami
                     mv * /d/target/
                     cd ..
                     rm -rf build
                     

          env:
            HP_TOKEN: 
              ${{secrets.HP_TOKEN}}
