name: Simple Java Github Actions Experiment

on:
 push:
    branches:
        -dev-environment

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: creating folder
          run: |
            mkdir build
            cd build
            git pull origin dev-environment
        - name: setting up java
          uses: actions/setup-java@v3
          with:
            distribution: 'oracle'
            java-version: '11'

        - name: Compiling code
          run: javac HelloWorld.java

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: 192.168.55.108
            username: "ANIRUDDHA MALLADI"
            password: "@10tatorS"
            port: 22
            key: ${{secrets.SSH_PRIVATE_KEY}}
            script: |
                     whoami
                     mv * /d/target/
                     cd ..
                     rm -rf build
